### ISSUE TITLE
Crash at startup/ mod incompatibility?

### ISSUE THREAD

**Issue by Denali007** [Draylar/crimson-moon#31] opened 2021-09-01 18:26 UTC
Here is the crash report :(
Might be a mod incompatibility or just something else?

---- Minecraft Crash Report ----
// Don't do that.

Time: 9/1/21 8:14 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_310.<init>(class_310.java:541)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectMoonTexture(Lnet/minecraft/class_1060;Lnet/minecraft/class_2960;)V in crimson-moon.mixins.json:WorldRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap crimson-moon-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_310.<init>(class_310.java:541)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6299457704 bytes (6007 MB) / 8220835840 bytes (7840 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 128
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.14.1+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antiqueatlas: Antique Atlas 6.0.0-fabric
		appletreesrev: Apple Trees Revived 2.3b
		aqupdcaracal: Caracal mob 1.16-1.3.1
		aqupdgrizzly: Grizzly Bear mob 1.16-1.2.0
		artifacts: Artifacts 3.2.1+fabric
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bambootweaks: Bamboo Tweaks 2.0.1+1.16.5
		battletowers: Battle Towers 3.3.4-1.16.4
		bclib: BCLib 0.1.45
		bedspreads: Bedspreads 1.3.1-1.16.4
		betlad: Better ladders 1.0.1
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterend: Better End 0.9.8.5-pre
		betterf3: BetterF3 1.1.3
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betternether: Better Nether 5.0.7
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		bitsandchisels: BitsAndChisels 2.3.2
		blockshifter: Blockshifter 1.4.0+fabric-1.16.4
		blockus: Blockus 2.1.11+1.16.5
		blue_endless_jankson: jankson 1.2.0
		blur: Blur (Fabric) 2.1.0
		boredlight: BoredLight 1.0.0
		byg: BYG 1.3.4
		campanion: Campanion 1.3.5
		camsbackpacks: Cammie's Wearable Backpacks 1.3
		candlebackport: Candle Backport 1.0
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		carrier: Carrier 1.7.6
		cavebiomes: Cave Biomes 0.6.2
		chains: Chains-Link 1.16.2-2.0.1
		chatplus: chatplus 1.0.1
		chickendropfeathers: Chicken Drop Feathers 1.0
		chillager_mod: Chillager 1.1
		chime: Chime 1.1.3
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.4.0
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.5.50
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config-lite: cloth-config-lite 1.0.4
		cloth-config2: Cloth Config v4 4.11.26
		colwater: ColWater 1.4.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		comforts: Comforts 0.0.5-1.16.5
		cosmetic-armor: Cosmetic Armor 1.0.0
		couplings: Couplings 1.3.3
		craftable_god_apple: Craftable God Apple 1.0.0
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		croptopia: Croptopia 1.4.0
		curios: Curios API 0.0.13-1.16.5
		cursedorigins: CursedOrigins 1.1.4
		customportalapi: Custom Portals 0.0.1-beta32-1.16
		damagetint: Damage tint 1.1.0
		deep-dungeons: Deep Dungeons 1.0.0-1.16.5
		desolation: Desolation 1.1.2
		divine_missions: Divine Missions 1.0.0
		doggomod: Doggo Mod 1.0.2
		dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.14
		dyetherite: Dyetherite 1.0.0+1.16.4
		earthtojavamobs: Earth2Java 1.7.1+1.16.4
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		easyautocrafting: EasyAutoCrafting 1.1+1.16
		enderitemod: Enderite Mod 1.2.4
		endplus: End Plus Mod 1.0.0
		enhancedcelestials: Enhanced Celestials 2.0.4
		excessenchantmentsfabric: Excess Enchantments 1.1.0
		extrablocks: Nico's Extra Blocks 0.1
		extraorigins: Extra Origins 1.16.5-12
		fabric: Fabric API 0.39.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2b6fb8d77d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+efd7b8cf7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+95b14da07d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+5badb62d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+2f5f89687d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+5badb62d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f3e8589e7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+6afaa13c7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.2.0+e1956bbf7d
		fabricenchantments: Fabric Enchantments 0.4.1
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 1.1.0
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		faster-minecarts: Faster Minecarts 1.1.2
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		flytre_lib: FlytreLib 0.2.11
		fpsdisplay: FPS-Display 1.4.1+1.16.4
		fruitful: Fruitful 1.0.0
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.47
		gentlefawn: GentleFawn 1.1.4-MC1.16.5-fabric
		gildednetherite: Gilded Netherite 1.0.0
		globedimension: Chunk In A Globe 1.16.5-1.1.0
		go-fish: Go Fish 1.2.3-beta-1.16.5
		greater_eye: Greater Eye of Ender 1.1.5
		harvest: Harvest 1.2.12
		health_levels: Health Levels 1.0.0
		herdspanic: Herds Panic 1.0.1
		identity: Identity 1.13.2-1.16.5
		improved-stations: Improved Stations 2.0.3
		inventoryhud: Inventory HUD + 3.4.0
		io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.8.2
		iris: Iris 1.1.1
		itemmodelfix: Item Model Fix 1.0.2+1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kirin: Kirin UI 1.7-1.16.2
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lapiswarps: Lapis Warps 1.0.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.3+1.16.5
		library_of_exile: Library of Exile 1.0.14
		libstructure: LibStructure 1.5
		locki: Locki 0.2.1
		mannequins: Mannequins 1.0.1
		mcdar: MC Dungeons Artifacts 1.2.0
		microconfig: Microconfig 1.0.5
		minecraft: Minecraft 1.16.5
		mining_dims: Mining Dimensions 1.0.5
		mmorpg: Age of Exile 2.1.5
		mobz: MobZ 2.4.6
		modmenu: Mod Menu 1.16.13
		morebakedfoods: More Baked Foods 1.1.0
		morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
		moremessages: MoreMessages 1.3.0
		moretotems: More Totems 2.7.3
		mostructures: Mo' Structures 1.2.0-1.16.5
		netherstuff: nether stuff 1.2
		neutral_animals: Neutral Animals 1.0.0
		nile_archery: Nile Archery 1.0.0
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		origins: Origins 0.7.3
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		petowner: Pet Owner 1.8.0-1.16.5+
		phosphor: Phosphor 0.7.2+build.12
		pipe: Pipe 1.3.1
		playerabilitylib: Pal 1.2.2
		playtime_count: Playtime Counter (Fabric) 1.0.0
		pling: Pling 1.3.0
		polymorph: Polymorph 0.0.11-1.16.5
		portablenether: Portable Nether 1.0
		portaltags: Portal Tags 2.1.0
		pptowers: Pew Pew Towers 1.0.2
		presencefootsteps: Presence Footsteps r29+1.16.4
		quickshulker: Quick Shulker 1.1.14-1.16
		ratsmischief: Rat's Mischief 1.1.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		replaymod: Replay Mod 1.16.4-2.6.1
		repurposed_structures: Repurposed Structures 1.16.5-1.11.6-fabric
		requiem: Requiem 1.7.14
		requiemapi: Requiem-API 1.7.14
		respawnablepets: Respawnable Pets 1.16.5-2
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		satin: Satin 1.5.1
		schmucks: Schmucks 1.3.2
		shulkerboxtooltip: Shulker Box Tooltip 2.3.7+1.16.5
		shulkerutils: shulkerutils 1.0.1-1.16
		sodium: Sodium 0.2.0+IRIS3-build.49
		somnus: Somnus API 0.0.12-1.16.5
		spark: spark 1.6.0
		spruceui: SpruceUI 2.0.4+1.16
		stacc: Stacc 1.0.1
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.3
		structure-helpers: Structure Helpers 3.0.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		things: Things 0.1.4
		throwabletorch: ThrowableTorch 1.2
		timeinabottle: Time in a Bottle 1.3-mc1.16.4-fabric
		torohealth: ToroHealth Damage Indicators 1.16.5-fabric-6
		transparent_cosmetics: Transparent Cosmetics 1.2.0
		traverse: Traverse 3.3.3
		trinkets: Trinkets 2.6.7
		untitledduckmod: Untitled Duck Mod 0.2.2
		urns: Urns 1.0.0
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voyager: Voyager 1.0.0
		waystones: Waystones 2.0.1
		windchimes: Windchimes 1.1.1
		witherite: Witherite 0.0.3
		world_of_exile: World of Exile 1.2.4
		xaerominimap: Xaero's Minimap 21.16.0
		xaeroworldmap: Xaero's World Map 1.16.1
		xlpackets: XLPackets 1.1
		yungsapi: YUNG's API 1.16.5-Fabric-9
		zoob: Monster Of The Ocean Depths 3.0.0
	Launched Version: fabric-loader-0.11.6-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 128x AMD Ryzen Threadripper 3990x 64-Core Processor

**Comment by NebelNidas** [comment] 2021-10-08 18:47
Duplicate of #30.

**Closed as completed** 2022-03-26 01:47 UTC
