### ISSUE TITLE
Crimson moon failed to load after the 1st arrival

### ISSUE THREAD

**Issue by Samekichi** [Draylar/crimson-moon#5] opened 2020-07-03 11:30 UTC
On my 1.15.2 server the crimson moon can work as expected for the first arrival. However, starting from the second arrival, only a message saying "The crimson moon has arrived. " will be sent, and the rest of the features lose effects or perform inaccurately. The red texture of the moon, atmosphere, or rain will only maintain for an instant and then disappear lightning-fast, representing as a "red flash" on the screen. Besides, the crimson moon will arrive at any time instead of about 18:00 or later, for instance I met one at 14:30 under bright sunshine. 
For the config, I reduced mobs per chunk to 2, turned on red moon texture, modify the chance to 15, and disabled usage of bed (But I'm not sure whether those changes lead to this issue, cuz if I want to test it I'll need to wait about 20 game days for the crimson moon to arrive by default settings. )
Anyway I love the concept of this mod as it adds some very attractive themes and challenges that enrich my game experience, so thx for this mod and hope to see this issue being fixed!

**Comment by linzexin022** [comment] 2020-08-03 15:43
Met the same problem in 1.16.1, we were fed up this situation so I decided not to use it (at the state of crimson moon). However, after this, the time of our world stopped and jumped 20 days per tick. Here's the video I've recorded.
[2020-08-03_23-12-56.zip](https://github.com/Draylar/crimson-moon/files/5016917/2020-08-03_23-12-56.zip)

**Comment by Draylar** [comment] 2020-08-03 16:54
Took me a while to figure out the root cause of the issue, but it should be fixed in 1.2.0 (this is a 1.16.1 version). 

I had originally assumed "day time" was 0 -> 24000, and made all my calculations around that (assuming day time is never >24000). Turns out day time _doesn't_ have a limit, so the timing gets worse and worse as days go on. I am now calculating the actual day time from the world time, and disable the Crimson Moon while Daylight Cycle is off.

Let me know if you encounter any other issues related to this! Thanks for the reports.

**Closed as completed by Draylar** 2020-08-03 16:54 UTC

**Comment by linzexin022** [comment] 2020-08-05 03:37
I finally found out what cause the problem in my server!! It's the mod SleepVote!! I changed the gamerule /gamerule sleepPercentageRequired from 0.33 to 0 that SleepVote provided. Here's the game log in my game log:

[pool-4-thread-2/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connect timed out
at net.minecraft.class_4341.method_20998(class_4341.java:440) ~[intermediary-minecraft-1.16.1-client.jar:?]
at net.minecraft.class_4341.method_21029(class_4341.java:318) ~[intermediary-minecraft-1.16.1-client.jar:?]
at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-minecraft-1.16.1-client.jar:?]
at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-minecraft-1.16.1-client.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]

When I changed the percent, then messages came one by one every 2 secs. 
Ahhh I'm so happy to find out such an annoying problem!!
